# Generated by Django 4.2 on 2023-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_classroom_course_enrollment_course_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
