# Generated by Django 4.2 on 2023-05-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_classroom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('day', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.CreateModel(
            name='ScheduleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.course')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ManyToManyField(through='system.ScheduleCourse', to='system.schedule'),
        ),
    ]
